on :  
 push:
   branches: [ main ]
   pull_request:
     branches: [ main ]
jobs:
  buil_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: Instalar dependencias
      run: npm install

    - name: Lint del codigo
      run: npm run lint

    - name: Ejecutar pruebas
      run: npm test

    - name: Simular despliegue
      run: |
        echo "Despliegue simulado: la apliacion paso Lint y pruebas exitosamente."